name: knowledge-base-proto
version : "2.4"
services:
  attacks-mitigations-database:
    image: postgres
    restart: unless-stopped
    container_name: 'attacks-mitigations-database'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_SECRET}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
      - ./knowledge-base.sql:/docker-entrypoint-initdb.d/init.sql
  web-server:
    build: .
    container_name: 'web-server'
    ports:
      - "80:80"
