name: First Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install Docker Compose
        run: |
          sudo apt-get update
           sudo apt-get install -y curl  # Install curl if it's not already installed
            sudo curl -L "https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            docker-compose --version  # Verify the installed version

      - name: Test Docker containers
        env:
          DB_SECRET: ${{secrets.DB_SECRET}}
          DB_HOSTNAME: ${{vars.DB_HOSTNAME}}
          DB_PORT: ${{vars.DB_PORT}}
          DB_NAME: ${{vars.DB_NAME}}
          DB_USER: ${{vars.DB_USER}}
        run: |
          cd src
          docker-compose up -d

  test:
    needs: build
    runs-on: ubuntu-latest
    environment: local
    env:
      DB_SECRET: ${{secrets.DB_SECRET}}
      DB_HOSTNAME: ${{vars.DB_HOSTNAME}}
      DB_PORT: ${{vars.DB_PORT}}
      DB_NAME: ${{vars.DB_NAME}}
      DB_USER: ${{vars.DB_USER}}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Run Docker containers
        run: |
          cd src
          docker-compose up -d

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests web server
        run: pytest tests/test_web_server.py

      - name: Run tests api
        run: pytest tests/test_api.py
      
      - name: Stop Docker containers
        run: |
          cd src
          docker-compose down