name: First Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Test Docker containers
        run: |
          cd src
          docker-compose up

  test:
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      
      - name: Run Docker containers
        run: |
          cd src
          docker-compose up -d

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/test_web_server.py
      
      - name: Stop Docker containers
        run: docker-compose down